### ISSUE TITLE
[pycrate_asn1rt] Converting a Pycrate object into a dict makes ASN booleans into Python integers, but "set_val" expects a Python boolean

### ISSUE THREAD

**Issue by p1-mmr** [ANSSI-FR/pycrate#21]
When an user calls `pycrate_object.set_val(python_dictionary)` in order to serialize back a Python dictionary into a given Pycrate object, and some field in the given dictionary corresponds to an ASN.1 boolean, we check whether the corresponding value in the dictionary is a Python boolean in the [`pycrate_asn1rt.asnobj_basic.BOOL._safechk_val`](https://github.com/ANSSI-FR/pycrate/blob/master/pycrate_asn1rt/asnobj_basic.py#L137) function, and raise an error otherwise.

However, when converting a Pycrate object (produced from parsing a raw UPER payload) to a Python dictionary by doing `pycrate_object()`, the resulting dictionary will contain a Python integer with the value `0` or `1` instead of proper Python boolean.

Because of this, the Python dictionary produced by doing `python_dictionary = pycrate_object()` can't be fed back to the dictionary when calling `pycrate_object.set_val(python_dictionary)`.

Sample code to reproduce the issue:

```python
from pycrate_asn1dir import RRC3G

pycrate_object = RRC3G.Class_definitions.UL_DCCH_Message

pycrate_object.from_uper(b'K\x88\x00\x02\xa0\x00\x142\xaa\xd5\x06\xa5V\xa8\x8aH0D\x80\x01\x80\x01\x10\x0c\xc0\xd5\xd6)\x92\xc0(\t\x9e\xcaF\x04<H\t\x98B1\xee\x89\x9e\xbbe\xea\x11\x8ftL\xf5\xdb/=\xc3\x88!(u\xd0\xd13\xd7l\xb2\x00t\x072\xc6\xa0I\xed!\x17\xe4\x8a5\x92\x00\xa6\x06\x81')

python_dict = pycrate_object()

print(python_dict)

pycrate_object.set_val(python_dict)
```

Produced behavior: pycrate will complain that a dictionary field that should be boolean while it is an integer (not always on the same field, likely because we iterate over an unsorted dictionary somewhere):

```
>>> pycrate_object.set_val(python_dict)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/pycrate_asn1rt/asnobj.py", line 631, in set_val
    self._safechk_val(self._val)
  File "/usr/local/lib/python3.5/dist-packages/pycrate_asn1rt/asnobj_construct.py", line 566, in _safechk_val
    self._cont[k]._safechk_val(val[k])
  File "/usr/local/lib/python3.5/dist-packages/pycrate_asn1rt/asnobj_construct.py", line 82, in _safechk_val
    self._cont[val[0]]._safechk_val(val[1])
  File "/usr/local/lib/python3.5/dist-packages/pycrate_asn1rt/asnobj_construct.py", line 566, in _safechk_val
    self._cont[k]._safechk_val(val[k])
  File "/usr/local/lib/python3.5/dist-packages/pycrate_asn1rt/asnobj_construct.py", line 566, in _safechk_val
    self._cont[k]._safechk_val(val[k])
  File "/usr/local/lib/python3.5/dist-packages/pycrate_asn1rt/asnobj_construct.py", line 566, in _safechk_val
    self._cont[k]._safechk_val(val[k])
  File "/usr/local/lib/python3.5/dist-packages/pycrate_asn1rt/asnobj_construct.py", line 566, in _safechk_val
    self._cont[k]._safechk_val(val[k])
  File "/usr/local/lib/python3.5/dist-packages/pycrate_asn1rt/asnobj_construct.py", line 1946, in _safechk_val
    self._cont._safechk_val(v)
  File "/usr/local/lib/python3.5/dist-packages/pycrate_asn1rt/asnobj_construct.py", line 566, in _safechk_val
    self._cont[k]._safechk_val(val[k])
  File "/usr/local/lib/python3.5/dist-packages/pycrate_asn1rt/asnobj_construct.py", line 566, in _safechk_val
    self._cont[k]._safechk_val(val[k])
  File "/usr/local/lib/python3.5/dist-packages/pycrate_asn1rt/asnobj_construct.py", line 1946, in _safechk_val
    self._cont._safechk_val(v)
  File "/usr/local/lib/python3.5/dist-packages/pycrate_asn1rt/asnobj_construct.py", line 566, in _safechk_val
    self._cont[k]._safechk_val(val[k])
  File "/usr/local/lib/python3.5/dist-packages/pycrate_asn1rt/asnobj_basic.py", line 139, in _safechk_val
    raise(ASN1ObjErr('{0}: invalid value, {1!r}'.format(self.fullname(), val)))
pycrate_asn1rt.err.ASN1ObjErr: CompressedModeMeasCapabFDD.dl-MeasurementsFDD: invalid value, 1
```

A functional workaround is that we can add a line casting the value returned when doing `pycrate_object()` to a boolean (`self._val = bool(self._val)`) to the [`pycrate_asn1rt.asnobj_basic.BOOL._from_per`](https://github.com/ANSSI-FR/pycrate/blob/master/pycrate_asn1rt/asnobj_basic.py#L169) function.

However, this seems not optimal, because
* It does not seem consistent with the intent to perform this conversion through a look-up table (there is likely an error with the present code)
* It does not make that we accept integers when inputting back a Python dictionary into a Pycrate object, which could be a desirable feature

**Comment by mitshell** [comment]
Thanks for reporting. It seems we find a bug in Python:
```
>>> {1:True, 0:False, True:1, False:0}
{0: 0, 1: 1}
```

Commit https://github.com/ANSSI-FR/pycrate/commit/bb614f8e9da22a932b49747a9395e9b4cf37c8c9 solves this issue.
